version: "3.8"
services:
  client:
    build: ./client
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - PORT=80
      - HOST=http://host.docker.internal:4000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
  server:
    stdin_open: true
    tty: true
    build: ./server
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - SECRET=${SECRET}
      - MONGO_URI=${MONGO_URI}
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
    volumes:
      - ./server:/server
      - /server/node_modules