version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /client/node_modules
      - ./client:/client
    environment:
      - PORT=80
      - HOST=http://host.docker.internal:4000
    depends_on:
      - server
  server:
    stdin_open: true
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - SECRET=${SECRET}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./server:/server
      - /server/node_modules