name: client-test

on:
  push:
    branches:
      - develop
      - main
  pull_request:

defaults:
  run:
    working-directory: client

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      HOST: http://localhost:4000
    steps:
      - name: Set up Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache next build
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Run tests
        run: yarn test
