name: server-lint

on: [pull_request]

defaults:
  run:
    working-directory: server

jobs:
  serverlint:
    name: server-lint
    runs-on: ubuntu-latest
    steps:
      - name: add dependencies
        run: yarn --prefer-offline

      - name: Run linter
        run: yarn run lint
